### ISSUE TITLE
How can get lat/long in response of Google autocomplete api 

### ISSUE THREAD

**Issue by Shahbaz-Akram** [tryWabbit/Google-Api-Helper#3]
if let results = response.data as? [GApiResponse.Autocomplete], response.isValidFor(.autocomplete) {

}

**Comment by tryWabbit** [comment]
Hello @Shahbaz-Akram ,
As far as I know this version of autocomplete api doesn't lat-long for the place you've selected. You need to call the place information api after getting the placeid from autocomplete api. This functionality is implemented the project itself. just download the project and look up for didSelect delegate of tableView in ViewController. You'll find the necessary information there.

Let me know if you face any kind of issue.

Thanks for using this library.
