### ISSUE TITLE
Need 20+ result Using  GoogleApiHelper+Nearby  API

### ISSUE THREAD

**Issue by Rushang007** [tryWabbit/Google-Api-Helper#4]
Hi there,

I'm facing an issue in this(**Get all nearby places with extension 'GoogleApiHelper+Nearby'**) API. Every time I'm making a search for Restaurants in London and I'm getting only 20 places or 20 results. So, how can I obtain more than 20 places? Could you please help me to solve this issue? 

Thanks in advance

**Comment by tryWabbit** [comment]
Hello @Rushang007,
Thanks for using my library, I really appreciate it. Can you share what you're doing, the request you're making to get the nearby places so I can debug the issue.

**Comment by Rushang007** [comment]
I'm developing an App which is a Travel Guide App. This App will help the user to locate Popular places, Sea, Waterfall, Food and Drinks, Hotels, Transportation services of a particular city/country the user is planning to visit. So, as I mentioned, I'm getting only 20 such results for Hotel/Restaurants so could you please see what wrong I'm doing here.

Thanks,

**Comment by tryWabbit** [comment]
Can you show me your code so I can identify the error?

**Comment by Rushang007** [comment]
i used same code from your code nothing change anything

**Comment by tryWabbit** [comment]
You mean this
```
var input = GInput()
input.keyword = "Restaurants"
input.radius = 20000
var location = GLocation()
location.latitude = 26.273178
location.longitude = 73.009545
input.destinationCoordinate = location
NearbyExtension.shared.completion = { response in
    if let data = response.data as? [GApiResponse.NearBy], response.isValidFor(.nearBy){
        // all nearby places
    }
}
NearbyExtension.shared.getAllNearBy(input: input)
```

What are the inputs you are passing, post your code first so i can see what you are missing.

**Comment by Rushang007** [comment]
ok 
 var input = GInput()
        input.keyword = "Food and Drink"
        input.radius = 50000
        var location = GLocation()
        location.latitude = lat
        location.longitude = lng
        input.destinationCoordinate = location

NearbyExtension.shared.completion = { response in
            if let data = response.data as? [GApiResponse.NearBy], response.isValidFor(.nearBy){
                // all nearby places
                print(data)
            }
        }
        NearbyExtension.shared.getAllNearBy(input: input)

**Comment by tryWabbit** [comment]
As far as I know the maximum limit is 50k and sometimes it doesn't give result for some places where locations are not available.
if you need nearby locations try with some short values like 20k meters it'll give you the results.

**Comment by Rushang007** [comment]
have you tasted same code (my code ) in your side ?

**Comment by tryWabbit** [comment]
I'm sorry to say this Rushang but please check your code first can you tell me what is lat and lng ? No body in this world can identify what is lat and lng, off course its a variable please post the values you are passing to make the request.

**Comment by Rushang007** [comment]
its current location lat and lng.

**Comment by Rushang007** [comment]
@tryWabbit  any update?
