### ISSUE TITLE
google api key error occured?

### ISSUE THREAD

**Issue by sourabhsharmait** [tryWabbit/Google-Api-Helper#7]
After providing google api key.. Still its showing error. Please check
![Screenshot 2020-01-30 at 5 59 35 PM](https://user-images.githubusercontent.com/12099495/73450005-71ae0800-438a-11ea-9711-a5417d8aaa9d.png)

**Comment by tryWabbit** [comment]
Thanks for using my library @sourabhsharmait ,
I'm sure you didn't have your billing address registered with your google account that you're using for api key. Please confirm if you have valid billing address. 

Google restrict the api usage after a limit and a particular time. 
Please provide details about it.
Thanks

**Comment by tryWabbit** [comment]
@sourabhsharmait  Please post your code so I can debug further, Thanks.

**Comment by sourabhsharmait** [comment]
Yes.. You are right.. I was using non billabe key... Thank you for correction...


And thank you for this great work....
